# Source: jxboot-helmfile-resources/templates/jenkins-x-docker-registry.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-x-docker-registry
  annotations:
    expose.config.fabric8.io/clusterip-port-if-empty-key: docker.registry
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
data:
  kaniko.flags: "--insecure"
  docker.registry: docker-registry-jx.127.0.0.1.xip.io
