apiVersion: v1
data:
  plugins.yaml: |
    approve:
    - lgtm_acts_as_approve: true
      repos:
      - jstrachan/jx3-demo-minikube
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - jstrachan/nodey488
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - jstrachan/nodey489
      require_self_approval: true
    blunderbuss: {}
    cat: {}
    cherry_pick_unapproved: {}
    config_updater:
      gzip: false
      maps:
        env/prow/config.yaml:
          name: config
        env/prow/plugins.yaml:
          name: plugins
    heart: {}
    label:
      additional_labels: null
    owners: {}
    plugins:
      jstrachan/jx3-demo-minikube:
      - config-updater
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - size
      - trigger
      - wip
      - heart
      - cat
      - override
      - dog
      - pony
      jstrachan/nodey488:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      jstrachan/nodey489:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
    requiresig: {}
    sigmention: {}
    size:
      l: 0
      m: 0
      s: 0
      xl: 0
      xxl: 0
    slack: {}
    triggers:
    - repos:
      - jstrachan/jx3-demo-minikube
      trusted_org: todo
    - repos:
      - jstrachan/nodey488
      trusted_org: todo
    - repos:
      - jstrachan/nodey489
      trusted_org: todo
    welcome:
    - message_template: Welcome
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: plugins
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
