apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      orgs:
        jstrachan:
          repos:
            jx3-demo-minikube:
              required_status_checks:
                contexts:
                - promotion-build
            nodey488:
              required_status_checks:
                contexts:
                - pr-build
            nodey489:
              required_status_checks:
                contexts:
                - pr-build
      protect-tested-repos: true
    deck:
      spyglass: {}
    gerrit: {}
    github:
      LinkURL: null
    plank: {}
    pod_namespace: jx
    postsubmits:
      jstrachan/jx3-demo-minikube:
      - agent: tekton
        branches:
        - master
        name: promotion
        skip_report: true
      jstrachan/nodey488:
      - agent: tekton
        branches:
        - master
        name: release
        skip_report: true
      jstrachan/nodey489:
      - agent: tekton
        branches:
        - master
        name: release
        skip_report: true
    presubmits:
      jstrachan/jx3-demo-minikube:
      - agent: tekton
        always_run: true
        context: promotion-build
        name: promotion-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      jstrachan/nodey488:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
      jstrachan/nodey489:
      - agent: tekton
        always_run: true
        context: pr-build
        name: pr-build
        rerun_command: /test this
        trigger: (?m)^/test( all| this),?(\s+|$)
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    sinker: {}
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        jstrachan/jx3-demo-minikube: merge
        jstrachan/nodey488: merge
        jstrachan/nodey489: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/jx3-demo-minikube
        - jstrachan/nodey488
        - jstrachan/nodey489
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jstrachan/jx3-demo-minikube
        - jstrachan/nodey488
        - jstrachan/nodey489
      target_url: http://deck-jx.192.168.64.4.nip.io
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
